@echo off
setlocal

set "Server=YourServerName"
set "Database=Defaultdatabase"
set "User=username"
set "Password=password"
set "SqlFile1=sqlfile1path.sql"            //Procedure files to run, add path here
set "SqlFile2=sqlfiel2path.sql"            // you can add as many files and as many executions


set "LogFile=%~dp0\ExecutionLog.txt"						//Log file creation to check for errors            // creates a log file to read logs later to see if procedure already exists or not

echo Running SQL file: %SqlFile1%
sqlcmd -S %Server% -d %Database% -U %User% -P %Password% -i %SqlFile1% >> %LogFile% 2>&1
if %errorlevel% neq 0 (
    echo Error executing %SqlFile1%
    goto :error
)

echo Running SQL file: %SqlFile2%
sqlcmd -S %Server% -d %Database% -U %User% -P %Password% -i %SqlFile2% >> %LogFile% 2>&1
if %errorlevel% neq 0 (
    echo Error executing %SqlFile2%
    goto :error
)

echo The above procedures executed successfully!               
echo Script generated by mutual efforts of Tariz and ChatGPT
goto :end

:error
echo Procedures failed to execute. Check the log file for details: %LogFile%

:end
pause
endlocal
